# Generated by Django 3.2.15 on 2022-08-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login1',
            new_name='data',
        ),
    ]
